### ISSUE TITLE
This dependency was not found: @znck/prop-types

### ISSUE THREAD

**Issue by wagerfield** [znck/lazy-hydration#2]
Since `@znck/prop-types` is not listed as a `dependency` of this package, it is not installed with `lazy-hydration`. Though `@znck/prop-types` is technically for development as documented in its README, I think it should be added as a dependency to `lazy-hydration` so that users don't run into the error:

    This dependency was not found: @znck/prop-types

**Comment by 777genius** [comment]
I have the same error:

> Cannot find module '@znck/prop-types'

 Not sure if [this](https://github.com/znck/lazy-hydration/blob/master/package.json#L30) is in the right place.
