### ISSUE TITLE
expected.flat is not a function

### ISSUE THREAD

**Issue by wagerfield** [znck/lazy-hydration#3]
Further to my previous issue (#2) after installing `@znck/prop-types` as a dev dependency, I am now seeing the error:

    expected.flat is not a function

Stack trace:

```js
static collectionOf(type, expected) {
  const prop = this.create(type);
  const types = expected.flat().map(normalizeType);

  prop.validator = value => Object.values(value).every(item => types.some(type => runValidation(type, item)));

  return prop;
}
```

Digging into this, I can see that `collectionOf` is called internally by `arrayOf` and `objectOf` (within the `@znck/prop-types` package) and that `expected` is an Array. This error is therefore coming from the fact that the `Array` instance in Node 10.15.0 doesn't have the `flat` method on it.

I am using Nuxt, so this error is coming from the server (with a very recent version of Nod) and not the client.

**Comment by znck** [comment]
Thanks for giving this detailed account. I'm fixing it ASAP.

**Comment by znck** [comment]
It's fixed and released (https://github.com/znck/lazy-hydration/runs/55170555)
