### ISSUE TITLE
when-visible not working

### ISSUE THREAD

**Issue by mrphilipandrews** [znck/lazy-hydration#7]
I cant seem to get **when-visible** to work. I'm seeing some malformed inline-style in the html too (attached)

![Screen Shot 2019-08-14 at 3 45 48 pm](https://user-images.githubusercontent.com/505776/62997364-59653200-beab-11e9-8016-70a9462983d8.png)

Seem to have the same issue **ssr-only**

**when-idle** is working fine

"intersection-observer": "^0.7.0",
"lazy-hydration": "^0.2.2",
"nuxt": "^2.8.1",

**Comment by znck** [comment]
Fixed in https://github.com/znck/lazy-hydration/releases/tag/v1.0.4

See: http://lazy-hydration.herokuapp.com/
