### ISSUE TITLE
Why does <Hydrate> allows only one child component?

### ISSUE THREAD

**Issue by natewallis** [znck/lazy-hydration#8]
I am not aware of the internals of how this library works, but worth mentioning that if you wrap a v-for, then only the first element renders.   My template looks like this:

```
    <hydrate on-hover>
      <catalog-product v-if="!loading" v-for="product in products" :key="product.product_id" :product="product" @display_quick_view="show_overlay" @hide_quick_view="hide_overlay"></catalog-product>
    </hydrate>
```

It works well, but I only end up with one element...

**Comment by znck** [comment]
`<Hydrate>` is an abstract component, which means it does not render anything, something like `<RouterView>`. However, `<Hydrate>` does need to store the state of hydration, hence it is stateful. In Vue 2.x, a stateful component can not have multiple root nodes. So, `<Hydrate>` takes the first child and ignores everything else.

Though, we have a workaround for the above situation:

```html
<hydrate on-hover>
   <div style="display: contents">
       <catalog-product v-if="!loading" v-for="product in products" :key="product.product_id" :product="product" @display_quick_view="show_overlay" @hide_quick_view="hide_overlay"></catalog-product>
   </div>
</hydrate>
```

Display Contents: https://caniuse.com/#feat=css-display-contents
